name: Build and Push Docker Image to AWS ECR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up AWS credentials using GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 202533509557.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - run: ls -al
        continue-on-error: true
      - run: cd target
        continue-on-error: true
      - run: ls -al
        continue-on-error: true

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Tag the Docker image with the ECR repository URI
      - name: Tag Docker image
        run: |
          docker tag myapp:latest 202533509557.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/docker-practice:latest

      # Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 202533509557.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/docker-practice:latest